import Racer from "../../types/racer";

export const RacerId = {
	HAM: "HAM",
	VET: "VET",
	BOT: "BOT",
	RAI: "RAI",
	RIC: "RIC",
	VER: "VER",
	PER: "PER",
	OCO: "OCO",
	HUL: "HUL",
	SAI: "SAI",
	STR: "STR",
	GRO: "GRO",
	MAG: "MAG",
	ALO: "ALO",
	VAN: "VAN",
	ERI: "ERI",
	GAS: "GAS",
	HAR: "HAR",
	LEC: "LEC",
	SIR: "SIR",
};

export const RACERS_MAP = new Map([
	[RacerId.HAM, new Racer("Lewis", "Hamilton", 44, RacerId.HAM)],
	[RacerId.VET, new Racer("Sebastian", "Vettel", 5, RacerId.VET)],
	[RacerId.BOT, new Racer("Valtteri", "Bottas", 77, RacerId.BOT)],
	[RacerId.RAI, new Racer("Kimi", "Raikkonen", 7, RacerId.RAI)],
	[RacerId.RIC, new Racer("Daniel", "Ricciardo", 3, RacerId.RIC)],
	[RacerId.VER, new Racer("Max", "Verstapen", 33, RacerId.VER)],
	[RacerId.PER, new Racer("Sergio", "Perez", 11, RacerId.PER)],
	[RacerId.OCO, new Racer("Esteban", "Ocon", 31, RacerId.OCO)],
	[RacerId.HUL, new Racer("Nico", "Hulkenberg", 27, RacerId.HUL)],
	[RacerId.SAI, new Racer("Carlos", "Sainz", 55, RacerId.SAI)],
	[RacerId.STR, new Racer("Lance", "Stroll", 18, RacerId.STR)],
	[RacerId.GRO, new Racer("Romain", "Grosjean", 8, RacerId.GRO)],
	[RacerId.MAG, new Racer("Kevin", "Magnussen", 20, RacerId.MAG)],
	[RacerId.ALO, new Racer("Fernando", "Alonso", 14, RacerId.ALO)],
	[RacerId.VAN, new Racer("Stoffel", "Vandoorne", 2, RacerId.VAN)],
	[RacerId.ERI, new Racer("Marcus", "Ericsson", 9, RacerId.ERI)],
	[RacerId.GAS, new Racer("Pierre", "Gasly", 10, RacerId.GAS)],
	[RacerId.HAR, new Racer("Brendon", "Hartley", 28, RacerId.HAR)],
	[RacerId.LEC, new Racer("Charles", "Leclerc", 16, RacerId.LEC)],
	[RacerId.SIR, new Racer("Sergey", "Sirotkin", 35, RacerId.SIR)],
]);
